[package]
name = "free_tunnel_sui"
edition = "2024.beta" 

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "2c930c25f8d3" }
mbtc = { local = "../mbtc-sui" }

[addresses]
free_tunnel_sui = "0x0"
mbtc = "0xd1a91b46bd6d966b62686263609074ad16cfdffc63c31a4775870a2d54d20c6b"

[dev-dependencies]

[dev-addresses]

